name: Build .NET Projects and deploy NuGet Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  

    env:
      Solution_Name: Ctrl2MqttBridge.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --configuration ${{ matrix.configuration }}

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }}
#      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
#      env:
#        Configuration: ${{ matrix.configuration }}

   

    # Create the app package by building and packaging the Windows Application Packaging project
    - name: Create the nuget package
      run: dotnet pack --configuration Release

    - name: print dir
      run: dir

    - name: Push NuGet package to NuGet.org
      env: 
        API_KEY: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push src\Ctrl2MqttClient\bin\Release\*.nupkg --api-key "$env:API_KEY" -s https://api.nuget.org/v3/index.json
